Screen developement
RealDoigt/Alien-Hack-D pull request #6
Opened 2022-10-08 17:43 UTC by sam00583

Fixed things from game-loop + added display_screen

2022-10-10 02:53 UTC, RealDoigt commented on data/source/menu/screens/main_menu.d
> +            new ClickableText(Screens.start, "Start", positionLabelX, positionLabelY + (20), 20),
parenthèses redondantes d'ici jusqu'à la ligne 10 autour des chiffres dans les appels de fonction. De plus, il semblerait qu'on pourrait avoir des constantes/enun ou des variables nommées ici au lieu du chiffre directement car il est très probable que ces chiffres changent lors du changement de résolution et aussi ces chiffres sont clairement répétés; en plus 40 et 60 sont clairement des multiples de 20...

2022-10-10 02:55 UTC, RealDoigt commented on data/source/menu/screens/save_game.d
> +
la convention du style d'écriture n'est pas respectée: les deux dernières virgules de l'appel du constructeur de Text ont un espacement incorrect. De plus, 20 pourrait être la même constante/variable suggérée ci-haut

2022-10-10 02:57 UTC, RealDoigt commented on data/source/menu/screens/success.d
> +            new ClickableText(Screens.main_menu, "Continue", positionLabelX, positionLabelY + (20), 20),
parenthèses redondantes + besoin de variable/constante comme demandé ci-haut

2022-10-10 03:00 UTC, RealDoigt requested changes
Salut, j'ai laissé d'autres commentaires sur des correctifs à faire! Ce sont des correctifs vraiment simple à corrigé. En passant, tu as oublié d'enlever les fichiers binaires. Il y en a trois.

2022-11-02 03:28 UTC, sam00583 commented
Changes have been made!

2022-11-02 05:18 UTC, RealDoigt approved these changes

2022-11-02 05:20 UTC, RealDoigt requested changes
désolé j'ai approuvé trop vite; il manque encore certains changements que j'ai demandé.

2022-11-05 14:25 UTC, RealDoigt approved these changes

2022-11-05 14:25 UTC, merged